#!/bin/bash

echo "🔧 DocsGPT n8n Workflow Import Helper"
echo ""
echo "To import the DocsGPT integration workflow:"
echo ""
echo "1. Open n8n web interface: http://localhost:5678"
echo "   Username: admin"
echo "   Password: password123"
echo ""
echo "2. Click on 'Workflows' in the left sidebar"
echo ""
echo "3. Click the '+' button to create a new workflow"
echo ""
echo "4. Click the '...' menu in the top right"
echo ""
echo "5. Select 'Import from file'"
echo ""
echo "6. Upload this file: $(pwd)/docsgpt_integration_workflow.json"
echo ""
echo "7. The workflow should import successfully"
echo ""
echo "8. Click 'Save' and then activate the workflow by toggling the 'Active' switch"
echo ""
echo "✅ Workflow will be available at:"
echo "   - Search/Answer: http://localhost:5678/webhook/docsgpt-integration"
echo "   - Document Upload: http://localhost:5678/webhook/docsgpt-document-upload"
echo ""
echo "💡 Alternative: You can also copy-paste the workflow JSON content directly"
echo "    into the n8n workflow editor if file upload doesn't work."