agent_settings:
  model_name: llama-3.1-8b-instant
  temperature: 0.1
  max_tokens: null
  processing_mode: thorough

tools:
  enabled_tools:
    - llamaparse_pdf
    - extract_and_store_entities
  tool_configs:
    llamaparse_pdf:
      enabled: true
      priority: 1
      required: true
      parameters:
        parsing_instruction: Extract all text and structure
    extract_and_store_entities:
      enabled: true
      priority: 1
      required: false
      parameters:
        confidence_threshold: 0.7
    store_vectors:
      enabled: true
      priority: 2
      required: false
      parameters:
        chunk_size: 500
        overlap: 50
    query_knowledge_graph:
      enabled: false
      priority: 3
      required: false
      parameters: {}

workflows:
  research_paper:
    description: Comprehensive analysis for academic papers
    tool_sequence:
      - llamaparse_pdf
      - extract_and_store_entities
      - store_vectors
    parallel_tools: []
    prompt_template:
      system_prompt: You are processing an academic research paper. Focus on extracting key concepts, methodologies, results, and citations.
      instruction_template: |
        Process the research paper at: {file_path}
        
        1. Extract and structure the content using llamaparse_pdf
        2. Identify and extract:
           - Key concepts and terminology
           - Research methodologies
           - Results and findings
           - Author citations and references
           - Relationships between concepts
        3. Store entities and relationships in the knowledge graph
        4. Create searchable text chunks for future reference
        
        Focus on academic rigor and comprehensive knowledge extraction.
      response_format: academic_summary
    success_criteria:
      - PDF parsed
      - Entities extracted
      - Knowledge graph updated
  
  general_document:
    description: Standard processing for typical documents
    tool_sequence:
      - llamaparse_pdf
      - extract_and_store_entities
    parallel_tools: []
    prompt_template:
      system_prompt: You are processing a general document. Extract key information and relationships.
      instruction_template: |
        Process the document at: {file_path}
        
        1. Extract content using llamaparse_pdf
        2. Identify key entities, concepts, and relationships
        3. Store the knowledge in the graph database
        
        Provide a clear summary of what was extracted and stored.
      response_format: standard_summary
    success_criteria:
      - PDF parsed
      - Content analyzed
      - Data stored
  
  fast:
    description: Quick processing with minimal analysis
    tool_sequence:
      - llamaparse_pdf
    parallel_tools: []
    prompt_template:
      system_prompt: ''
      instruction_template: |
        Quickly extract content from: {file_path}
        
        Use llamaparse_pdf to get the text content. 
        Provide a brief summary of the document content.
      response_format: brief_summary
    success_criteria:
      - PDF parsed
      - Summary provided

prompts:
  system_prompt: You are an intelligent document processing assistant.
  custom_instructions: ''
  response_format: structured_summary

processing:
  timeout_seconds: 300
  retry_attempts: 2
  parallel_processing: false

output:
  include_intermediate_results: true
  detailed_logging: false
  save_processing_trace: false